# Project Stage 1 Report

Group #3  
Project topic: Movie Revenue Forecasting  
Dataset url: https://www.kaggle.com/datasets/tmdb/tmdb-movie-metadata

## Task 1: Problem Framing (not done)

Your understanding of the project (what you want to study or predict).
Write 4-6 sentences describing: the task (classification/regression/..);
who/what benefits from this study; why this dataset fits (size, feature)

## Task 2: Dataset Exploration
### Importing the Dataset
Here we download the dataset directly from kaggle.

In [157]:
# Only need to run once to download dataset locally.
!pip install kagglehub pandas
import kagglehub
path = kagglehub.dataset_download("tmdb/tmdb-movie-metadata")

Requirement already satisfied: kagglehub in c:\users\matth\anaconda3\lib\site-packages (0.3.13)
Requirement already satisfied: pandas in c:\users\matth\anaconda3\lib\site-packages (2.2.3)
Requirement already satisfied: packaging in c:\users\matth\anaconda3\lib\site-packages (from kagglehub) (24.2)
Requirement already satisfied: pyyaml in c:\users\matth\anaconda3\lib\site-packages (from kagglehub) (6.0.2)
Requirement already satisfied: requests in c:\users\matth\anaconda3\lib\site-packages (from kagglehub) (2.32.3)
Requirement already satisfied: tqdm in c:\users\matth\anaconda3\lib\site-packages (from kagglehub) (4.67.1)
Requirement already satisfied: numpy>=1.26.0 in c:\users\matth\anaconda3\lib\site-packages (from pandas) (2.1.3)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\matth\anaconda3\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\matth\anaconda3\lib\site-packages (from pandas) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\matth\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\matth\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\matth\anaconda3\lib\site-packages (from requests->kagglehub) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in c:\users\matth\anaconda3\lib\site-packages (from requests->kagglehub) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\matth\anaconda3\lib\site-packages (from requests->kagglehub) (2.3.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\matth\anaconda3\lib\site-packages (from requests->kagglehub) (2025.4.26)
Requirement already satisfied: colorama in c:\users\matth\anaconda3\lib\site-packages (from tqdm->kagglehub) (0.4.6)

Next we load the 2 datasets into dataframs 'movies' and 'credits'.

In [158]:
# Need to run every time to import dataset into notebook.
import os
import pandas as pd

# import movies

csv_file = os.path.join(path, "tmdb_5000_movies.csv")
movies = pd.read_csv(csv_file)

# import credits

csv_file = os.path.join(path, "tmdb_5000_credits.csv")
credits = pd.read_csv(csv_file)

We perform an outer merge on the movie id, combining the dataframes.

In [159]:
# merge
df = pd.merge(movies, credits, left_on='id', right_on='movie_id', how='outer')

Here we display the first 10 rows of our dataset.

In [160]:
# First 10 rows (Stage 1, Task 2)
df.head(10)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,...,spoken_languages,status,tagline,title_x,vote_average,vote_count,movie_id,title_y,cast,crew
0,4000000,"[{""id"": 80, ""name"": ""Crime""}, {""id"": 35, ""name...",NaN,5,"[{""id"": 612, ""name"": ""hotel""}, {""id"": 613, ""na...",en,Four Rooms,It's Ted the Bellhop's first night on the job....,22.876230,"[{""name"": ""Miramax Films"", ""id"": 14}, {""name"":...",...,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,Twelve outrageous guests. Four scandalous requ...,Four Rooms,6.5,530,5,Four Rooms,"[{""cast_id"": 42, ""character"": ""Ted the Bellhop...","[{""credit_id"": ""52fe420dc3a36847f800012d"", ""de..."
1,11000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 28, ""...",http://www.starwars.com/films/star-wars-episod...,11,"[{""id"": 803, ""name"": ""android""}, {""id"": 4270, ...",en,Star Wars,Princess Leia is captured and held hostage by ...,126.393695,"[{""name"": ""Lucasfilm"", ""id"": 1}, {""name"": ""Twe...",...,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"A long time ago in a galaxy far, far away...",Star Wars,8.1,6624,11,Star Wars,"[{""cast_id"": 3, ""character"": ""Luke Skywalker"",...","[{""credit_id"": ""52fe420dc3a36847f8000437"", ""de..."
2,94000000,"[{""id"": 16, ""name"": ""Animation""}, {""id"": 10751...",http://movies.disney.com/finding-nemo,12,"[{""id"": 494, ""name"": ""father son relationship""...",en,Finding Nemo,"Nemo, an adventurous young clownfish, is unexp...",85.688789,"[{""name"": ""Pixar Animation Studios"", ""id"": 3}]",...,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"There are 3.7 trillion fish in the ocean, they...",Finding Nemo,7.6,6122,12,Finding Nemo,"[{""cast_id"": 8, ""character"": ""Marlin (voice)"",...","[{""credit_id"": ""52fe420ec3a36847f80006b1"", ""de..."
3,55000000,"[{""id"": 35, ""name"": ""Comedy""}, {""id"": 18, ""nam...",NaN,13,"[{""id"": 422, ""name"": ""vietnam veteran""}, {""id""...",en,Forrest Gump,A man with a low IQ has accomplished great thi...,138.133331,"[{""name"": ""Paramount Pictures"", ""id"": 4}]",...,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"The world will never be the same, once you've ...",Forrest Gump,8.2,7927,13,Forrest Gump,"[{""cast_id"": 7, ""character"": ""Forrest Gump"", ""...","[{""credit_id"": ""52fe420ec3a36847f800076b"", ""de..."
4,15000000,"[{""id"": 18, ""name"": ""Drama""}]",http://www.dreamworks.com/ab/,14,"[{""id"": 255, ""name"": ""male nudity""}, {""id"": 29...",en,American Beauty,"Lester Burnham, a depressed suburban father in...",80.878605,"[{""name"": ""DreamWorks SKG"", ""id"": 27}, {""name""...",...,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,Look closer.,American Beauty,7.9,3313,14,American Beauty,"[{""cast_id"": 6, ""character"": ""Lester Burnham"",...","[{""credit_id"": ""52fe420ec3a36847f8000809"", ""de..."
5,12800000,"[{""id"": 18, ""name"": ""Drama""}, {""id"": 80, ""name...",NaN,16,"[{""id"": 30, ""name"": ""individual""}, {""id"": 246,...",en,Dancer in the Dark,"Selma, a Czech immigrant on the verge of blind...",22.022228,"[{""name"": ""Fine Line Features"", ""id"": 8}, {""na...",...,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,You don't need eyes to see.,Dancer in the Dark,7.6,377,16,Dancer in the Dark,"[{""cast_id"": 33, ""character"": ""Selma Jezkova"",...","[{""credit_id"": ""52fe420ec3a36847f8000981"", ""de..."
6,90000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",NaN,18,"[{""id"": 402, ""name"": ""clone""}, {""id"": 444, ""na...",en,The Fifth Element,"In 2257, a taxi driver is unintentionally give...",109.528572,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...",...,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,There is no future without it.,The Fifth Element,7.3,3885,18,The Fifth Element,"[{""cast_id"": 5, ""character"": ""Korben Dallas"", ...","[{""credit_id"": ""52fe420fc3a36847f8000c09"", ""de..."
7,92620000,"[{""id"": 18, ""name"": ""Drama""}, {""id"": 878, ""nam...",NaN,19,"[{""id"": 312, ""name"": ""man vs machine""}, {""id"":...",de,Metropolis,In a futuristic city sharply divided between t...,32.351527,"[{""name"": ""Paramount Pictures"", ""id"": 4}, {""na...",...,"[{""iso_639_1"": ""xx"", ""name"": ""No Language""}]",Released,There can be no understanding between the hand...,Metropolis,8.0,657,19,Metropolis,"[{""cast_id"": 10, ""character"": ""Maria"", ""credit...","[{""credit_id"": ""52fe420fc3a36847f8000c55"", ""de..."
8,0,"[{""id"": 18, ""name"": ""Drama""}, {""id"": 10749, ""n...",http://www.clubcultura.com/clubcine/clubcineas...,20,"[{""id"": 455, ""name"": ""farewell""}, {""id"": 457, ...",en,My Life Without Me,A Pedro Almodovar production in which a fatall...,7.958831,"[{""name"": ""El Deseo"", ""id"": 49}, {""name"": ""Mil...",...,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,NaN,My Life Without Me,7.2,77,20,My Life Without Me,"[{""cast_id"": 5, ""character"": ""Ann"", ""credit_id...","[{""credit_id"": ""52fe420fc3a36847f8000d1d"", ""de..."
9,140000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneyvideos/liveaction/p...,22,"[{""id"": 911, ""name"": ""exotic island""}, {""id"": ...",en,Pirates of the Caribbean: The Curse of the Bla...,"Jack Sparrow, a freewheeling 17th-century pira...",271.972889,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...",...,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,Prepare to be blown out of the water.,Pirates of the Caribbean: The Curse of the Bla...,7.5,6985,22,Pirates of the Caribbean: The Curse of the Bla...,"[{""cast_id"": 12, ""character"": ""Captain Jack Sp...","[{""credit_id"": ""52fe420fc3a36847f8000f11"", ""de..."

### Dataset Dictionary
This code creates a dataset dictionary listing our 25 features, their data type, an example entry, and % entries missing. We also assigned revenue as our target feature.

In [161]:
# Task 2: Create a dataset dictionary
dataset_dict = pd.DataFrame({
    "Feature": df.columns,
    "Type": [df[col].dtype for col in df.columns],
    "Example": [df[col].dropna().iloc[0] for col in df.columns],  
    "Missing %": [df[col].isna().mean() * 100 for col in df.columns]
})

# Add target variable at the end
dataset_dict.loc[len(dataset_dict)] = [
    "Target Variable (revenue)",  
    df["revenue"].dtype,         
    df["revenue"].dropna().iloc[0], 
    df["revenue"].isna().mean() * 100 
]

dataset_dict

,Feature,Type,Example,Missing %
0,budget,int64,4000000,0.000000
1,genres,object,"[{""id"": 80, ""name"": ""Crime""}, {""id"": 35, ""name...",0.000000
2,homepage,object,http://www.starwars.com/films/star-wars-episod...,64.355611
3,id,int64,5,0.000000
4,keywords,object,"[{""id"": 612, ""name"": ""hotel""}, {""id"": 613, ""na...",0.000000
5,original_language,object,en,0.000000
6,original_title,object,Four Rooms,0.000000
7,overview,object,It's Ted the Bellhop's first night on the job....,0.062461
8,popularity,float64,22.87623,0.000000
9,production_companies,object,"[{""name"": ""Miramax Films"", ""id"": 14}, {""name"":...",0.000000
10,production_countries,object,"[{""iso_3166_1"": ""US"", ""name"": ""United States o...",0.000000
11,release_date,object,1995-12-09,0.020820
12,revenue,int64,4300000,0.000000
13,runtime,float64,98.0,0.041641
14,spoken_languages,object,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",0.000000
15,status,object,Released,0.000000
16,tagline,object,Twelve outrageous guests. Four scandalous requ...,17.572351
17,title_x,object,Four Rooms,0.000000
18,vote_average,float64,6.5,0.000000
19,vote_count,int64,530,0.000000
20,movie_id,int64,5,0.000000
21,title_y,object,Four Rooms,0.000000
22,cast,object,"[{""cast_id"": 42, ""character"": ""Ted the Bellhop...",0.000000
23,crew,object,"[{""credit_id"": ""52fe420dc3a36847f800012d"", ""de...",0.000000
24,Target Variable (revenue),int64,4300000,0.000000

## Task 3 — Feature Exploration 
### Abdel
I cleaned a few features:

- runtime: filled missing values with the median
- budget and revenue: replaced 0 with NaN
- homepage and tagline: dropped because they had too many missing

Now the data looks cleaner for later analysis.

In [162]:
import numpy as np

df["runtime"] = df["runtime"].fillna(df["runtime"].median())

df["budget"] = df["budget"].replace(0, np.nan)
df["revenue"] = df["revenue"].replace(0, np.nan)

df = df.drop(["homepage","tagline"], axis=1)

print("cleaned runtime, budget, revenue, homepage, tagline")

cleaned runtime, budget, revenue, homepage, tagline

### Matthew

Before merging, both data sets had identical 'id' and 'title' columns, which created duplicates in the merge. So, I removed the duplicates, making a single 'id' and 'title' column.

In [163]:
df = df.drop(["movie_id"], axis=1)
df = df.drop(["title_y"], axis=1)
df = df.rename(columns={"title_x": "title"})

Lots of the columns were hard to read, and looked to be stored as a dictionary, so I converted them into comma separated lists.  
Example: '[{"id": 80, "name": "Crime"}, {"id": 35, "name": "Comedy"}]' becomes 'Crime, Comedy'

In [164]:
import ast

# List of columns that need conversion
json_cols = ['genres', 'keywords', 'cast', 'production_companies', 'production_countries', 'spoken_languages', 'crew']

for col in json_cols:
    df[col] = df[col].apply(lambda s: ", ".join(d['name'] for d in ast.literal_eval(s)) if s else "")

Reordered columns to group similar columns, and follow the general order of id, target, numeric data, lists, metadata.

In [165]:
df = df[['id', 'revenue', 'budget', 'runtime', 'popularity', 'vote_average', 'vote_count', 'genres', 'keywords', 'cast', 'crew', 'production_companies', 'production_countries', 'spoken_languages', 'title', 'original_title', 'overview', 'release_date', 'status', 'original_language']]

In [178]:
numeric_cols = ['budget', 'runtime', 'popularity', 'vote_average', 'vote_count']

# Compute mean and standard deviation
means = df[numeric_cols].mean().round()
stds = df[numeric_cols].std().round()

# Define outlier thresholds: mean ± 3*std
thresholds = pd.DataFrame({
    'Lower': (means - 3*stds).round(),
    'Upper': (means + 3*stds).round()
})

# Print outlier values, means, and thresholds
for col in numeric_cols:
    lower = int(thresholds.loc[col, 'Lower'])
    upper = int(thresholds.loc[col, 'Upper'])
    print(f"{col} mean: {int(means[col])}")
    print(f"{col} outlier thresholds: {lower} - {upper}")
    
    high_outliers = df[df[col] > upper][col].round().astype(int).values
    low_outliers = df[df[col] < lower][col].round().astype(int).values
    
    print(f"{col} high outliers: {high_outliers}")
    print(f"{col} low outliers: {low_outliers}\n")

budget mean: 37042838
budget outlier thresholds: -90896704 - 164982380
budget high outliers: [200000000 185000000 185000000 207000000 300000000 200000000 180000000
 200000000 200000000 258000000 200000000 175000000 250000000 270000000
 380000000 215000000 180000000 225000000 175000000 165000000 170000000
 175000000 200000000 165000000 165000000 200000000 180000000 200000000
 200000000 175000000 200000000 175000000 175000000 200000000 237000000
 170000000 200000000 220000000 210000000 200000000 195000000 260000000
 225000000 170000000 209000000 200000000 165000000 200000000 250000000
 250000000 225000000 260000000 190000000 250000000 255000000 170000000
 185000000 200000000 175000000 200000000 180000000 200000000 200000000
 170000000 176000003 195000000 165000000 210000000 280000000 170000000
 200000000 180000000 175000000 170000000 170000000 250000000 250000000
 178000000 175000000 165000000 190000000 190000000 165000000 185000000
 245000000 250000000 170000000 178000000 180000000 250000000 175000000
 175000000]
budget low outliers: []

runtime mean: 107
runtime outlier thresholds: 38 - 176
runtime high outliers: [178 179 201 177 200 187 178 229 188 207 195 189 178 181 194 183 238 191
 189 186 197 216 202 199 197 184 192 248 178 225 193 180 177 242 254 192
 219 183 191 193 181 214 188 199 195 200 185 338 180 276 180 240 191 200]
runtime low outliers: [25  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0 14  0  0  0  0  0
  0  0  0  0  0  0  0  0  0  0  0  0  0]

popularity mean: 21
popularity outlier thresholds: -75 - 117
popularity high outliers: [126 138 272 146 138 124 119 187 144 137 139 128 147 132 121 121 135 127
 150 144 168 138 125 434 202 137 143 134 120 165 481 244 121 118 206 127
 419 129 724 130 204 132 145 156 143 876 140 193 139 141 198 168 515]
popularity low outliers: []

vote_average mean: 6
vote_average outlier thresholds: 3 - 9
vote_average high outliers: [10  9 10 10 10 10]
vote_average low outliers: [1 3 3 2 3 0 3 3 0 0 2 0 0 3 3 0 0 0 0 2 0 0 2 0 0 0 3 2 0 0 0 0 0 0 0 0 2
 0 0 0 0 0 0 0 1 0 0 0 0 3 0 0 0 2 0 0 0 2 0 0 0 2 2 0 0 3 2 0 0 0 0 0 0 0
 0 3 0 0 0 0 0 0 0 0 0 0 0 0]

vote_count mean: 690
vote_count outlier thresholds: -3015 - 4395
vote_count high outliers: [ 6624  6122  7927  6985  4949  5246  5439  6079  8705  7487  8064 12002
  5893  7359  4443  8205  4500  4856  4470  9413  5265  5996  7562  8907
  4412  7006  5815  5877  5608  5494  8428  4442  5293  5765  5048  5269
  4997  8776  7047  4948  5879  4665  4432  6586  4853  5376  5152  6849
  4597  6525  5766  6296  6336  4645  4518  6870  4903  6430  6173 11800
  6478  4645 11776 13752  4537  7604  4430  9106  5751  8297  6359  5181
  4418  4524  4697  4641 10099  8806  4794  9455  5080  4697  5560  4800
  5487  4755  9427  4570  4742  5797  4637  6767  5764  6495  4496  5880
  6571  5295  9742  4410  4519  4760  6032  5584  8662  4858  6560 10867
  4663  6135  4469  4535  5371  5723  4466  7004  5862  4571  5878  4721
  4737  7241  6396  7268 10995  7458]
vote_count low outliers: []

In [181]:
import numpy as np
from scipy.stats import zscore

numeric_cols = ['budget', 'runtime', 'popularity', 'vote_average', 'vote_count']

# Compute mean and std for outlier thresholds
means = df[numeric_cols].mean()
stds = df[numeric_cols].std()

# Define thresholds
lower = means - 3*stds
upper = means + 3*stds

# Identify outliers per column
outliers = (df[numeric_cols] < lower) | (df[numeric_cols] > upper)

# Identify NaNs per column
nans = df[numeric_cols].isna()

# Rows with any outlier
rows_with_outlier = outliers.any(axis=1)

# Rows with any NaN
rows_with_nan = nans.any(axis=1)

total_rows = len(df)
num_rows_with_outlier = rows_with_outlier.sum()
num_rows_with_nan = rows_with_nan.sum()

print(f"Total rows: {total_rows}")
print(f"Rows with any outlier: {num_rows_with_outlier}")
print(f"Rows with any NaN: {num_rows_with_nan}")

Total rows: 4803
Rows with any outlier: 339
Rows with any NaN: 1037

In [184]:
numeric_cols = ['budget', 'runtime', 'popularity', 'vote_average', 'vote_count']

# Compute mean and std for outlier thresholds
means = df[numeric_cols].mean()
stds = df[numeric_cols].std()

# Define thresholds
lower = means - 3*stds
upper = means + 3*stds

# For each row, check numeric columns for outliers
for idx, row in df.iterrows():
    outlier_list = []
    for col in numeric_cols:
        if pd.isna(row[col]):
            continue  # skip NaN
        if row[col] > upper[col]:
            outlier_list.append(f"{col}: high")
        elif row[col] < lower[col]:
            outlier_list.append(f"{col}: low")
    
    if outlier_list:  # Only print rows with at least one outlier
        print(f"Title: {row['title']}")
        print(f"Outliers: {outlier_list}\n")

Title: Star Wars
Outliers: ['popularity: high', 'vote_count: high']

Title: Finding Nemo
Outliers: ['vote_count: high']

Title: Forrest Gump
Outliers: ['popularity: high', 'vote_count: high']

Title: Pirates of the Caribbean: The Curse of the Black Pearl
Outliers: ['popularity: high', 'vote_count: high']

Title: Kill Bill: Vol. 1
Outliers: ['vote_count: high']

Title: Pirates of the Caribbean: Dead Man's Chest
Outliers: ['budget: high', 'popularity: high', 'vote_count: high']

Title: Gladiator
Outliers: ['vote_count: high']

Title: Back to the Future
Outliers: ['vote_count: high']

Title: The Lord of the Rings: The Fellowship of the Ring
Outliers: ['runtime: high', 'popularity: high', 'vote_count: high']

Title: The Lord of the Rings: The Two Towers
Outliers: ['runtime: high', 'vote_count: high']

Title: The Lord of the Rings: The Return of the King
Outliers: ['runtime: high', 'popularity: high', 'vote_count: high']

Title: Spirited Away
Outliers: ['popularity: high']

Title: The Dark Knight
Outliers: ['budget: high', 'popularity: high', 'vote_count: high']

Title: Braveheart
Outliers: ['runtime: high']

Title: Indiana Jones and the Kingdom of the Crystal Skull
Outliers: ['budget: high']

Title: The Godfather
Outliers: ['runtime: high', 'popularity: high', 'vote_count: high']

Title: The Godfather: Part II
Outliers: ['runtime: high']

Title: King Kong
Outliers: ['budget: high', 'runtime: high']

Title: Batman Begins
Outliers: ['vote_count: high']

Title: The Silence of the Lambs
Outliers: ['vote_count: high']

Title: The Shawshank Redemption
Outliers: ['popularity: high', 'vote_count: high']

Title: Pirates of the Caribbean: At World's End
Outliers: ['budget: high', 'popularity: high', 'vote_count: high']

Title: Terminator 3: Rise of the Machines
Outliers: ['budget: high']

Title: Meet Joe Black
Outliers: ['runtime: high']

Title: Once Upon a Time in America
Outliers: ['runtime: high']

Title: Jurassic Park
Outliers: ['vote_count: high']

Title: Magnolia
Outliers: ['runtime: high']

Title: Once Upon a Time in the West
Outliers: ['runtime: high']

Title: Seven Samurai
Outliers: ['runtime: high']

Title: Alien
Outliers: ['vote_count: high']

Title: The Chronicles of Narnia: The Lion, the Witch and the Wardrobe
Outliers: ['budget: high']

Title: Schindler's List
Outliers: ['runtime: high']

Title: The Green Mile
Outliers: ['runtime: high']

Title: One Flew Over the Cuckoo's Nest
Outliers: ['popularity: high']

Title: Casino
Outliers: ['runtime: high']

Title: Terminator Salvation
Outliers: ['budget: high']

Title: Fight Club
Outliers: ['popularity: high', 'vote_count: high']

Title: Spider-Man
Outliers: ['vote_count: high']

Title: Spider-Man 2
Outliers: ['budget: high']

Title: Spider-Man 3
Outliers: ['budget: high']

Title: Dances with Wolves
Outliers: ['runtime: high']

Title: Monsters, Inc.
Outliers: ['vote_count: high']

Title: Titanic
Outliers: ['budget: high', 'runtime: high', 'vote_count: high']

Title: The Matrix
Outliers: ['vote_count: high']

Title: Men in Black
Outliers: ['vote_count: high']

Title: Troy
Outliers: ['budget: high']

Title: Harry Potter and the Philosopher's Stone
Outliers: ['vote_count: high']

Title: Harry Potter and the Chamber of Secrets
Outliers: ['popularity: high', 'vote_count: high']

Title: Harry Potter and the Prisoner of Azkaban
Outliers: ['vote_count: high']

Title: Harry Potter and the Goblet of Fire
Outliers: ['vote_count: high']

Title: Harry Potter and the Order of the Phoenix
Outliers: ['vote_count: high']

Title: Pearl Harbor
Outliers: ['runtime: high']

Title: Pulp Fiction
Outliers: ['popularity: high', 'vote_count: high']

Title: V for Vendetta
Outliers: ['vote_count: high']

Title: Harry Potter and the Half-Blood Prince
Outliers: ['budget: high', 'vote_count: high']

Title: Gone with the Wind
Outliers: ['runtime: high']

Title: Gandhi
Outliers: ['runtime: high']

Title: Se7en
Outliers: ['vote_count: high']

Title: JFK
Outliers: ['runtime: high']

Title: Judgment at Nuremberg
Outliers: ['runtime: high']

Title: Saving Private Ryan
Outliers: ['vote_count: high']

Title: Toy Story
Outliers: ['vote_count: high']

Title: Doctor Zhivago
Outliers: ['runtime: high']

Title: Lawrence of Arabia
Outliers: ['runtime: high']

Title: 300
Outliers: ['vote_count: high']

Title: Superman Returns
Outliers: ['budget: high']

Title: Iron Man
Outliers: ['popularity: high', 'vote_count: high']

Title: Captain America: The First Avenger
Outliers: ['vote_count: high']

Title: Pirates of the Caribbean: On Stranger Tides
Outliers: ['budget: high', 'popularity: high', 'vote_count: high']

Title: Malcolm X
Outliers: ['runtime: high']

Title: The Empire Strikes Back
Outliers: ['vote_count: high']

Title: Return of the Jedi
Outliers: ['vote_count: high']

Title: Star Wars: Episode I - The Phantom Menace
Outliers: ['vote_count: high']

Title: The Amazing Spider-Man
Outliers: ['budget: high', 'vote_count: high']

Title: Alexander
Outliers: ['runtime: high']

Title: The Golden Compass
Outliers: ['budget: high']

Title: The Greatest Story Ever Told
Outliers: ['runtime: high']

Title: The Chronicles of Narnia: Prince Caspian
Outliers: ['budget: high']

Title: Evan Almighty
Outliers: ['budget: high']

Title: Intolerance
Outliers: ['runtime: high']

Title: Barry Lyndon
Outliers: ['runtime: high']

Title: Veer-Zaara
Outliers: ['runtime: high']

Title: The Polar Express
Outliers: ['budget: high']

Title: A Bridge Too Far
Outliers: ['runtime: high']

Title: I Am Legend
Outliers: ['vote_count: high']

Title: Cleopatra
Outliers: ['runtime: high']

Title: Wild Wild West
Outliers: ['budget: high']

Title: The Lion King
Outliers: ['vote_count: high']

Title: Twilight
Outliers: ['popularity: high']

Title: The Longest Day
Outliers: ['runtime: high']

Title: Woodstock
Outliers: ['runtime: high']

Title: The Right Stuff
Outliers: ['runtime: high']

Title: Bound by Honor
Outliers: ['runtime: high']

Title: Waterworld
Outliers: ['budget: high']

Title: The Incredibles
Outliers: ['vote_count: high']

Title: The Postman
Outliers: ['runtime: high']

Title: Iron Man 2
Outliers: ['budget: high', 'vote_count: high']

Title: How to Train Your Dragon
Outliers: ['budget: high']

Title: Shrek Forever After
Outliers: ['budget: high']

Title: Toy Story 3
Outliers: ['budget: high', 'vote_count: high']

Title: Thor
Outliers: ['vote_count: high']

Title: Sherlock Holmes
Outliers: ['vote_count: high']

Title: Hamlet
Outliers: ['runtime: high']

Title: Gettysburg
Outliers: ['runtime: high']

Title: WALL·E
Outliers: ['budget: high', 'vote_count: high']

Title: Quantum of Solace
Outliers: ['budget: high']

Title: Nixon
Outliers: ['runtime: high']

Title: All Hat
Outliers: ['vote_average: low']

Title: Heaven's Gate
Outliers: ['runtime: high']

Title: Shutter Island
Outliers: ['vote_count: high']

Title: The Deer Hunter
Outliers: ['runtime: high']

Title: Alice in Wonderland
Outliers: ['budget: high', 'vote_count: high']

Title: Wyatt Earp
Outliers: ['runtime: high']

Title: A Charlie Brown Christmas
Outliers: ['runtime: low']

Title: Star Trek
Outliers: ['vote_count: high']

Title: Up
Outliers: ['budget: high', 'vote_count: high']

Title: 2012
Outliers: ['budget: high', 'vote_count: high']

Title: Kabhi Alvida Naa Kehna
Outliers: ['runtime: high']

Title: Fiddler on the Roof
Outliers: ['runtime: high']

Title: G.I. Joe: The Rise of Cobra
Outliers: ['budget: high']

Title: Monsters vs Aliens
Outliers: ['budget: high']

Title: Gods and Generals
Outliers: ['runtime: high']

Title: Inglourious Basterds
Outliers: ['vote_count: high']

Title: The Fall of the Roman Empire
Outliers: ['runtime: high']

Title: Anne of Green Gables
Outliers: ['runtime: high']

Title: A Christmas Carol
Outliers: ['budget: high']

Title: Reds
Outliers: ['runtime: high']

Title: The Hangover
Outliers: ['vote_count: high']

Title: Avatar
Outliers: ['budget: high', 'popularity: high', 'vote_count: high']

Title: Chocolate: Deep Dark Secrets
Outliers: ['runtime: high']

Title: Despicable Me
Outliers: ['vote_count: high']

Title: TRON: Legacy
Outliers: ['budget: high']

Title: Robin Hood
Outliers: ['budget: high']

Title: Kick-Ass
Outliers: ['vote_count: high']

Title: The Avengers
Outliers: ['budget: high', 'popularity: high', 'vote_count: high']

Title: Inception
Outliers: ['popularity: high', 'vote_count: high']

Title: The Legend of Suriyothai
Outliers: ['runtime: high']

Title: Superbabies: Baby Geniuses 2
Outliers: ['vote_average: low']

Title: X-Men: The Last Stand
Outliers: ['budget: high']

Title: The Truman Show
Outliers: ['vote_count: high']

Title: Skyfall
Outliers: ['budget: high', 'vote_count: high']

Title: Transformers: Dark of the Moon
Outliers: ['budget: high']

Title: Tangled
Outliers: ['budget: high']

Title: The Blood of My Brother: A Story of Death in Iraq
Outliers: ['vote_average: low']

Title: Little Big Top
Outliers: ['runtime: low', 'vote_average: high']

Title: Men in Black 3
Outliers: ['budget: high']

Title: Blood Done Sign My Name
Outliers: ['runtime: low']

Title: Carlos
Outliers: ['runtime: high']

Title: Fabled
Outliers: ['vote_average: low']

Title: Black Swan
Outliers: ['vote_count: high']

Title: Hugo
Outliers: ['budget: high']

Title: Battleship
Outliers: ['budget: high']

Title: Green Lantern
Outliers: ['budget: high']

Title: Rust
Outliers: ['vote_average: low']

Title: Neal 'n' Nikki
Outliers: ['vote_average: low']

Title: Fighting Tommy Riley
Outliers: ['runtime: low']

Title: Independence Day: Resurgence
Outliers: ['budget: high']

Title: Cars 2
Outliers: ['budget: high']

Title: The Dark Knight Rises
Outliers: ['budget: high', 'vote_count: high']

Title: Gravity
Outliers: ['vote_count: high']

Title: The Hobbit: An Unexpected Journey
Outliers: ['budget: high', 'vote_count: high']

Title: Man of Steel
Outliers: ['budget: high', 'vote_count: high']

Title: John Carter
Outliers: ['budget: high']

Title: X-Men: First Class
Outliers: ['vote_count: high']

Title: Certifiably Jonathan
Outliers: ['vote_average: low']

Title: Creature
Outliers: ['runtime: high']

Title: The Salon
Outliers: ['runtime: low']

Title: Hav Plenty
Outliers: ['vote_average: low']

Title: The Tooth Fairy
Outliers: ['runtime: low']

Title: Star Trek Into Darkness
Outliers: ['budget: high', 'vote_count: high']

Title: The Hobbit: The Desolation of Smaug
Outliers: ['budget: high', 'vote_count: high']

Title: The Lone Ranger
Outliers: ['budget: high']

Title: Snow White and the Huntsman
Outliers: ['budget: high']

Title: Looper
Outliers: ['vote_count: high']

Title: Rise of the Planet of the Apes
Outliers: ['popularity: high']

Title: Brave
Outliers: ['budget: high', 'popularity: high', 'vote_count: high']

Title: Monsters University
Outliers: ['budget: high']

Title: 47 Ronin
Outliers: ['budget: high']

Title: N-Secure
Outliers: ['runtime: low']

Title: Django Unchained
Outliers: ['vote_count: high']

Title: Iron Man 3
Outliers: ['budget: high', 'vote_count: high']

Title: Pacific Rim
Outliers: ['budget: high', 'vote_count: high']

Title: Oz: The Great and Powerful
Outliers: ['budget: high']

Title: The Legend of God's Gun
Outliers: ['vote_average: low']

Title: The Hunger Games
Outliers: ['vote_count: high']

Title: The Harvest (La Cosecha)
Outliers: ['vote_average: low']

Title: Prometheus
Outliers: ['vote_count: high']

Title: Ted
Outliers: ['vote_count: high']

Title: World War Z
Outliers: ['budget: high', 'vote_count: high']

Title: Dil Jo Bhi Kahey...
Outliers: ['runtime: low', 'vote_average: low']

Title: Oblivion
Outliers: ['vote_count: high']

Title: Now You See Me
Outliers: ['vote_count: high']

Title: Thor: The Dark World
Outliers: ['budget: high', 'vote_count: high']

Title: Mad Max: Fury Road
Outliers: ['popularity: high', 'vote_count: high']

Title: Jupiter Ascending
Outliers: ['budget: high']

Title: Dancer, Texas Pop. 81
Outliers: ['vote_average: high']

Title: Four Single Fathers
Outliers: ['vote_average: low']

Title: Jack the Giant Slayer
Outliers: ['budget: high']

Title: Wreck-It Ralph
Outliers: ['budget: high', 'vote_count: high']

Title: Silver Linings Playbook
Outliers: ['vote_count: high']

Title: Terminator Genisys
Outliers: ['popularity: high']

Title: Life of Pi
Outliers: ['vote_count: high']

Title: Stiff Upper Lips
Outliers: ['vote_average: high']

Title: Transformers: Age of Extinction
Outliers: ['budget: high']

Title: Despicable Me 2
Outliers: ['popularity: high', 'vote_count: high']

Title: Straight Out of Brooklyn
Outliers: ['runtime: low']

Title: Teenage Mutant Ninja Turtles
Outliers: ['popularity: high']

Title: Avengers: Age of Ultron
Outliers: ['budget: high', 'popularity: high', 'vote_count: high']

Title: Captain America: The Winter Soldier
Outliers: ['budget: high', 'vote_count: high']

Title: The Hunger Games: Catching Fire
Outliers: ['vote_count: high']

Title: The Amazing Spider-Man 2
Outliers: ['budget: high']

Title: Maleficent
Outliers: ['budget: high', 'vote_count: high']

Title: Sex With Strangers
Outliers: ['runtime: low']

Title: Ant-Man
Outliers: ['popularity: high', 'vote_count: high']

Title: The Good Dinosaur
Outliers: ['budget: high']

Title: The Wolf of Wall Street
Outliers: ['runtime: high', 'vote_count: high']

Title: Below Zero
Outliers: ['runtime: low']

Title: Frozen
Outliers: ['popularity: high', 'vote_count: high']

Title: The Company
Outliers: ['runtime: high']

Title: The Oogieloves in the Big Balloon Adventure
Outliers: ['vote_average: low']

Title: Should've Been Romeo
Outliers: ['runtime: low', 'vote_average: low']

Title: Down & Out With The Dolls
Outliers: ['vote_average: low']

Title: Foodfight!
Outliers: ['vote_average: low']

Title: Guardians of the Galaxy
Outliers: ['budget: high', 'popularity: high', 'vote_count: high']

Title: Dawn of the Planet of the Apes
Outliers: ['budget: high', 'popularity: high', 'vote_count: high']

Title: El Rey de Najayo
Outliers: ['vote_average: low']

Title: The Grand Budapest Hotel
Outliers: ['vote_count: high']

Title: The Hobbit: The Battle of the Five Armies
Outliers: ['budget: high', 'popularity: high', 'vote_count: high']

Title: X-Men: Days of Future Past
Outliers: ['budget: high', 'popularity: high', 'vote_count: high']

Title: The Hunger Games: Mockingjay - Part 1
Outliers: ['popularity: high', 'vote_count: high']

Title: The Hunger Games: Mockingjay - Part 2
Outliers: ['popularity: high']

Title: Jab Tak Hai Jaan
Outliers: ['runtime: high']

Title: Jurassic World
Outliers: ['popularity: high', 'vote_count: high']

Title: Edge of Tomorrow
Outliers: ['budget: high', 'vote_count: high']

Title: The Young Unknowns
Outliers: ['vote_average: low']

Title: Elza
Outliers: ['vote_average: low']

Title: The Frozen
Outliers: ['runtime: low']

Title: Inside Out
Outliers: ['budget: high', 'popularity: high', 'vote_count: high']

Title: Restless
Outliers: ['runtime: high']

Title: Tin Can Man
Outliers: ['vote_average: low']

Title: Interstellar
Outliers: ['budget: high', 'popularity: high', 'vote_count: high']

Title: Divergent
Outliers: ['vote_count: high']

Title: How to Fall in Love
Outliers: ['runtime: low']

Title: Tomorrowland
Outliers: ['budget: high', 'popularity: high']

Title: The Big Swap
Outliers: ['runtime: low', 'vote_average: low']

Title: Furious 7
Outliers: ['budget: high']

Title: The Deported
Outliers: ['vote_average: low']

Title: Big Hero 6
Outliers: ['budget: high', 'popularity: high', 'vote_count: high']

Title: Carousel of Revenge
Outliers: ['vote_average: low']

Title: Emma
Outliers: ['runtime: high']

Title: Star Trek Beyond
Outliers: ['budget: high']

Title: Love in the Time of Monsters
Outliers: ['runtime: low']

Title: American Sniper
Outliers: ['vote_count: high']

Title: Short Cut to Nirvana: Kumbh Mela
Outliers: ['vote_average: low']

Title: Birdman
Outliers: ['vote_count: high']

Title: Mutual Friends
Outliers: ['runtime: low', 'vote_average: low']

Title: The Maze Runner
Outliers: ['popularity: high', 'vote_count: high']

Title: The Vatican Exorcisms
Outliers: ['runtime: low']

Title: The Imitation Game
Outliers: ['popularity: high', 'vote_count: high']

Title: Spectre
Outliers: ['budget: high', 'vote_count: high']

Title: Batman v Superman: Dawn of Justice
Outliers: ['budget: high', 'popularity: high', 'vote_count: high']

Title: Gone Girl
Outliers: ['popularity: high', 'vote_count: high']

Title: Vessel
Outliers: ['runtime: low']

Title: Minions
Outliers: ['popularity: high', 'vote_count: high']

Title: The Ballad of Gregorio Cortez
Outliers: ['vote_average: low']

Title: Sparkler
Outliers: ['vote_average: low']

Title: Her Cry: La Llorona Investigation
Outliers: ['vote_average: low']

Title: Taxman
Outliers: ['vote_average: low']

Title: Fury
Outliers: ['popularity: high']

Title: Dwegons
Outliers: ['vote_average: low']

Title: Lucy
Outliers: ['vote_count: high']

Title: Alice Through the Looking Glass
Outliers: ['budget: high']

Title: Whiplash
Outliers: ['popularity: high']

Title: X-Men: Apocalypse
Outliers: ['budget: high', 'popularity: high', 'vote_count: high']

Title: Butterfly Girl
Outliers: ['vote_average: low']

Title: Pixels
Outliers: ['popularity: high']

Title: The Legend of Tarzan
Outliers: ['budget: high']

Title: Water & Power
Outliers: ['runtime: low']

Title: Ex Machina
Outliers: ['vote_count: high']

Title: The Work and The Story
Outliers: ['vote_average: low']

Title: Captain America: Civil War
Outliers: ['budget: high', 'popularity: high', 'vote_count: high']

Title: Dude Where's My Dog?
Outliers: ['runtime: low', 'vote_average: low']

Title: Give Me Shelter
Outliers: ['vote_average: low']

Title: The Jungle Book
Outliers: ['budget: high']

Title: Harrison Montgomery
Outliers: ['runtime: low', 'vote_average: low']

Title: House at the End of the Drive
Outliers: ['vote_average: low']

Title: Gory Gory Hallelujah
Outliers: ['runtime: low', 'vote_average: low']

Title: Fort McCoy
Outliers: ['runtime: low']

Title: The Revenant
Outliers: ['vote_count: high']

Title: An American in Hollywood
Outliers: ['vote_average: low']

Title: Alleluia! The Devil's Carnival
Outliers: ['runtime: low']

Title: Grindhouse
Outliers: ['runtime: high']

Title: The Martian
Outliers: ['popularity: high', 'vote_count: high']

Title: Sanctuary: Quite a Conundrum
Outliers: ['vote_average: low']

Title: Stories of Our Lives
Outliers: ['vote_average: low']

Title: Archaeology of a Woman
Outliers: ['vote_average: low']

Title: Deadpool
Outliers: ['popularity: high', 'vote_count: high']

Title: The Outrageous Sophie Tucker
Outliers: ['vote_average: low']

Title: Queen of the Mountains
Outliers: ['vote_average: low']

Title: The Hadza:  Last of the First
Outliers: ['vote_average: low']

Title: The Little Ponderosa Zoo
Outliers: ['vote_average: low']

Title: Suicide Squad
Outliers: ['budget: high', 'vote_count: high']

Title: Death Calls
Outliers: ['runtime: low', 'vote_average: low']

Title: Naturally Native
Outliers: ['vote_average: low']

Title: Black Water Transit
Outliers: ['vote_average: low']

Title: Bleeding Hearts
Outliers: ['runtime: low', 'vote_average: low']

Title: UnDivided
Outliers: ['runtime: low', 'vote_average: low']

Title: The Horror Network Vol. 1
Outliers: ['runtime: low']

Title: Anderson's Cross
Outliers: ['vote_average: low']

Title: Hum To Mohabbat Karega
Outliers: ['runtime: low', 'vote_average: low']

Title: Diamond Ruff
Outliers: ['runtime: low', 'vote_average: low']

Title: Dawn of the Crescent Moon
Outliers: ['vote_average: low']

Title: Rise of the Entrepreneur: The Search for a Better Way
Outliers: ['runtime: low']

Title: Light from the Darkroom
Outliers: ['runtime: low', 'vote_average: low']

Title: Antarctic Edge: 70° South
Outliers: ['vote_average: low']

Title: Windsor Drive
Outliers: ['vote_average: low']

Title: The World Is Mine
Outliers: ['vote_average: low']

Title: Sardaarji
Outliers: ['runtime: low']

Title: Heroes of Dirt
Outliers: ['vote_average: low']

Title: The Blade of Don Juan
Outliers: ['vote_average: low']

Title: Karachi se Lahore
Outliers: ['runtime: low']

Title: The Algerian

### Trey

I went and looked over all data to ensure the set was clean. 
After analysis, it seems we have cleaned the data set well and taken into account entries that werent proper and replaced them with NAN (not a number) to ensure the system doesnt read them and skew the data. Doing this ensures that the means or averages are not skewed for things like Budget and Revenue.

### Liyah

### Shauna

## Task 4 — Save Cleaned Data 

I saved the cleaned dataset as data/newdata.csv. 
This file will be used for the rest of the project.

In [167]:
import os

# save cleaned dataframe
os.makedirs("data", exist_ok=True)
df.to_csv("data/newdata.csv", index=False, encoding="utf-8")

print("saved cleaned dataset to data/newdata.csv")

saved cleaned dataset to data/newdata.csv